name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Shaurya07dev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub Pages (output branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

